// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbpzvcixoocdtzqvtwfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZicHp2Y2l4b29jZHR6cXZ0d2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNTkzNTUsImV4cCI6MjA2ODczNTM1NX0.g_RCJill8N9I_19sanPLob7gDdjp1TjxzeKvZCJCxl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});